### ISSUE TITLE
Dialog not visible in fullscreen mode 

### ISSUE THREAD

**Issue by D-Groenewegen** [dbmdz/mirador-canvaslink#63]
First of all, thank you for putting in all the great work! I'm really glad the plugin allows me to output and share a URL with a specific canvas id. 

I found a minor bug which is similar to one which previously also affected the ImageCropper plugin. When the Mirador viewer is launched into fullscreen mode, everything else that's not contained below the element with class="fullscreen" is hidden. As a result, the popup dialog that normally appears when the CanvasLink menu button is hit remains invisible. 

I suppose that the solution would be similar to that implemented for ImageCropper in v0.1.3.

**Comment by morpheus-87** [comment]
Thank you very much for reporting this bug :+1: the fix is released in version `0.2.2`.
